-- 코드를 입력하세요
SELECT A.ANIMAL_ID
     ,A.ANIMAL_TYPE
     ,A.NAME
FROM ANIMAL_INS A
         INNER JOIN (
    SELECT ANIMAL_ID, SEX_UPON_OUTCOME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME IN('Neutered Male','Spayed Female')
) AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE NOT IN ('Neutered Male','Spayed Female')
ORDER BY 1